"""rename department

Revision ID: 491186fc6a82
Revises: 9bddbf0db576
Create Date: 2023-11-16 11:51:30.458985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491186fc6a82'
down_revision = '9bddbf0db576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
